### ISSUE TITLE
Generics method parameters can't resolved and cause error

### ISSUE THREAD

**Issue by Plutoz01** [thiagobustamante/typescript-rest-swagger#23]
Given the following base class:

``` typescript
export interface Identifiable<I> {
	id?: I
}

export abstract class CrudControllerBase <T extends Identifiable<ID>, ID> {

	@GET
	@Path( ':entityId' )
	async getById( @PathParam( 'entityId' ) id: ID ): Promise<T> {
		// some logic to retrieve item
	}
}
```

and the extending child class:
``` typescript
@Path( '/users' )
export class UserController extends CrudControllerBase<User, string> {
	// ...
}
```

Child controller works fine and serves request, but during swagger generation (`swaggerGen -c ./swaggerConfig.json`) the base class's `id: ID` parameter throws error:

```
C:\dev\typescript-rest-swagger\dist\metadata\methodGenerator.js:57
                throw new Error("Error generate parameter method: '" + controllerId.text + "." + methodId.text + "' argument: " + parameterId.text + " " + e);
                ^

Error: Error generate parameter method: 'CrudControllerBase.getById' argument: id TypeError: Cannot read property 'kind' of undefined
    at C:\dev\typescript-rest-swagger\dist\metadata\methodGenerator.js:57:23
    at Array.map (<anonymous>)
    at MethodGenerator.buildParameters (C:\dev\typescript-rest-swagger\dist\metadata\methodGenerator.js:49:47)
    at MethodGenerator.generate (C:\dev\typescript-rest-swagger\dist\metadata\methodGenerator.js:37:30)
    at C:\dev\typescript-rest-swagger\dist\metadata\controllerGenerator.js:61:58
    at Array.map (<anonymous>)
    at ControllerGenerator.buildMethodsForClass (C:\dev\typescript-rest-swagger\dist\metadata\controllerGenerator.js:61:14)

    at ControllerGenerator.buildMethods (C:\dev\typescript-rest-swagger\dist\metadata\controllerGenerator.js:44:43)
    at ControllerGenerator.generate (C:\dev\typescript-rest-swagger\dist\metadata\controllerGenerator.js:29:27)
    at C:\dev\typescript-rest-swagger\dist\metadata\metadataGenerator.js:67:58
```

Typescript version: 2.5.3
Full source of files :
[crud-base-controller.ts](https://github.com/Plutoz01/ts-rest-starter/blob/master/src/controllers/base/crud-base.controller.ts)
[user.controller.ts](https://github.com/Plutoz01/ts-rest-starter/blob/master/src/controllers/user.controller.ts)

Would it possible to totally ignore abstract classes during generation (like CrudControllerBase in the example above)? They don't handle any real paths, so it should not listen in the generated swagger output at all.

**Comment by kelvin-evari** [comment]
Hi, is there any updates from this issue? It was raised 2 years ago and no comments at all 🤷‍♂ 🤷‍♂ 🤷‍♂ 
We are having the same issue and we have to make our types not generic because of this issue.
